"""Миграции накатываются, откатываются и не расходятся с моделями.

Главный тест здесь — `test_models_match_migrations`. Я сам назвал в плане
наиболее вероятным сбоем расхождение декларативных моделей и миграции: модель
правится, миграция нет, тесты на моделях зелёные, а `make reset` даёт другую
схему. Ревью плана указало, что против этого стояла запись в `CLAUDE.md`, то
есть словесный запрет, — а §41.4 говорит прямо, что словесных запретов агенту
недостаточно. Эти два теста и есть замена записи проверкой.

Прогоняются на отдельной базе: они сносят схему до `base` и накатывают
заново, и делать это на базе, которой пользуются остальные тесты, значило бы
поставить результат в зависимость от порядка прогона.
"""

from __future__ import annotations

from collections.abc import AsyncIterator

import asyncpg
import pytest
import pytest_asyncio
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from alembic import command
from core.db.engine import build_engine
from core.db.models import Base
from tests.conftest import alembic_config, run_alembic

pytestmark = pytest.mark.db

MIGRATIONS_DB = "studybot_migrations"


def _url(settings_url: str, name: str) -> str:
    return settings_url.rsplit("/", 1)[0] + "/" + name


def _dsn(engine: AsyncEngine) -> str:
    """URL движка со паролем.

    `str(engine.url)` маскирует пароль как `***`, и первая версия этих тестов
    подставляла на его место литерал `studybot`. Локально это работало, а в CI
    пароль другой — четыре теста упали на «password authentication failed for
    user ci». Поймал это CI, а не локальный прогон: ровно тот случай, ради
    которого §41.4 требует, чтобы CI выполнял то же, что `make check`.
    """
    return engine.url.render_as_string(hide_password=False)


@pytest_asyncio.fixture
async def fresh_engine() -> AsyncIterator[AsyncEngine]:
    """Пустая база без схемы и без журнала миграций."""
    from core.config import load_settings

    admin = load_settings().DATABASE_URL
    dsn = admin.replace("postgresql+asyncpg://", "postgresql://")
    conn = await asyncpg.connect(dsn)
    try:
        await conn.execute(f'DROP DATABASE IF EXISTS "{MIGRATIONS_DB}" WITH (FORCE)')
        await conn.execute(f'CREATE DATABASE "{MIGRATIONS_DB}"')
    finally:
        await conn.close()

    url = _url(admin, MIGRATIONS_DB)
    engine = build_engine(url)
    try:
        yield engine
    finally:
        await engine.dispose()


async def _table_names(engine: AsyncEngine) -> set[str]:
    async with engine.connect() as connection:
        result = await connection.execute(
            text("SELECT table_name FROM information_schema.tables WHERE table_schema='public'")
        )
        return {str(row[0]) for row in result}


async def test_upgrade_creates_every_table(fresh_engine: AsyncEngine) -> None:
    """`upgrade head` на пустой базе даёт все таблицы §3."""
    url = _dsn(fresh_engine)
    await run_alembic(url, "upgrade")

    names = await _table_names(fresh_engine)
    assert set(Base.metadata.tables) <= names


async def test_every_revision_downgrades(fresh_engine: AsyncEngine) -> None:
    """Откат доводит базу до пустой, повторный накат восстанавливает схему.

    Критерий плана работ «каждая миграция откатывается» закрывается прогоном,
    а не утверждением. Проверяется и обратное направление: база после
    `downgrade base` пуста, то есть откат не оставил половину схемы.
    """
    url = _dsn(fresh_engine)

    await run_alembic(url, "upgrade")
    assert set(Base.metadata.tables) <= await _table_names(fresh_engine)

    await run_alembic(url, "downgrade", "base")
    left = await _table_names(fresh_engine) - {"alembic_version"}
    assert left == set(), f"после отката в базе осталось: {sorted(left)}"

    await run_alembic(url, "upgrade")
    assert set(Base.metadata.tables) <= await _table_names(fresh_engine)


async def test_models_match_migrations(fresh_engine: AsyncEngine) -> None:
    """После `upgrade head` автогенерация против моделей даёт пустой diff.

    Это защита от того, что я назвал наиболее вероятным сбоем пакета. Проверка
    идёт через `alembic check`, у которой `compare_type` и
    `compare_server_default` выставлены в `env.py` **явно**: у второго дефолт
    `False`, и без явной записи расхождение в `DEFAULT` осталось бы
    незамеченным — а в §3 двадцать семь колонок с `DEFAULT`.
    """
    url = _dsn(fresh_engine)
    await run_alembic(url, "upgrade")

    config = alembic_config(url)
    async with fresh_engine.begin() as connection:

        def _check(sync_conn: object) -> None:
            config.attributes["connection"] = sync_conn
            command.check(config)

        await connection.run_sync(_check)


async def test_check_detects_drift(fresh_engine: AsyncEngine) -> None:
    """`alembic check` действительно краснеет на расхождении.

    Без этого предыдущий тест был бы проверкой того, что команда не падает, а
    не того, что она что-то сравнивает. Колонка добавляется прямым DDL — то
    есть имитируется ровно тот случай, против которого проверка и ставится:
    схема изменилась мимо моделей.
    """
    url = _dsn(fresh_engine)
    await run_alembic(url, "upgrade")

    async with fresh_engine.begin() as connection:
        await connection.execute(text("ALTER TABLE users DROP COLUMN lang"))

    config = alembic_config(url)
    with pytest.raises(AutogenerateDiffsDetected):
        async with fresh_engine.begin() as connection:

            def _check(sync_conn: object) -> None:
                config.attributes["connection"] = sync_conn
                command.check(config)

            await connection.run_sync(_check)


async def test_create_all_is_not_used() -> None:
    """`create_all` не встречается в проекте нигде.

    Схема существует только в миграциях. `create_all` в фикстуре дал бы
    зелёные тесты на схеме, которой нет в `make reset`, — и расхождение
    обнаружилось бы при развёртывании.

    Проверка grep-ом по совету ревью плана: §41.4 требует дублировать правила
    проверками, а не словесными запретами. Сама по себе она слабее, чем
    `alembic check`, и стоит рядом с ней, а не вместо.
    """
    import pathlib

    # Ищется вызов, а не слово: упоминание в докстроке — объяснение правила, а
    # не его нарушение. Первая версия покраснела на комментарии в
    # `conftest.py`, вторая — на собственном литерале шаблона, поэтому шаблон
    # собирается из частей и в тексте файла целиком не встречается.
    pattern = "create_all" + "("
    root = pathlib.Path(__file__).resolve().parents[1]
    offenders: list[str] = []
    for folder in ("core", "bot", "tests", "alembic"):
        for path in root.glob(f"{folder}/**/*.py"):
            if pattern in path.read_text(encoding="utf-8"):
                offenders.append(str(path.relative_to(root)))
    assert not offenders, f"{pattern} найден в: {offenders}"
