"""schema

Revision ID: 0001
Revises:
Create Date: 2026-10-05 23:29:31.259635+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_calls",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("material_id", sa.BigInteger(), nullable=True),
        sa.Column("purpose", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("pricing_version", sa.Text(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_currency", sa.Text(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(), nullable=True),
        sa.Column("actual_cost", sa.Numeric(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("tz", sa.Text(), server_default="Europe/Moscow", nullable=True),
        sa.Column("quiet_from", sa.Time(), server_default="23:00", nullable=True),
        sa.Column("quiet_to", sa.Time(), server_default="08:00", nullable=True),
        sa.Column("daily_cap", sa.Integer(), server_default="60", nullable=True),
        sa.Column("new_per_day", sa.Integer(), server_default="20", nullable=True),
        sa.Column("session_size", sa.Integer(), server_default="6", nullable=True),
        sa.Column("lang", sa.Text(), server_default="ru", nullable=True),
        sa.Column("paused", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("plan", sa.Text(), server_default="free", nullable=True),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tg_id"),
    )
    op.create_table(
        "subjects",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("subject_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("origin", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("mode", sa.Text(), server_default="full", nullable=True),
        sa.Column("completed_stages", sa.ARRAY(sa.Text()), server_default="{}", nullable=True),
        sa.Column("progress", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cost_estimate", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["subject_id"],
            ["subjects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_materials_sha256", "materials", [sa.literal_column("(origin->>'sha256')")], unique=False
    )
    op.create_index(
        "uq_materials_user_sha256",
        "materials",
        ["user_id", sa.literal_column("(origin->>'sha256')")],
        unique=True,
        postgresql_where=sa.text("origin ? 'sha256'"),
    )
    op.create_table(
        "media_assets",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("material_id", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.Text(), nullable=True),
        sa.Column("mime", sa.Text(), nullable=True),
        sa.Column("w", sa.Integer(), nullable=True),
        sa.Column("h", sa.Integer(), nullable=True),
        sa.Column("tg_file_id", sa.Text(), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("material_id", sa.BigInteger(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("summary_md", sa.Text(), nullable=True),
        sa.Column("fragment_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.Column("material_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("control_message_id", sa.BigInteger(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_sessions_user_active",
        "sessions",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "facts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("material_id", sa.BigInteger(), nullable=False),
        sa.Column("section_id", sa.BigInteger(), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.Column("fragment_ids", sa.ARRAY(sa.Integer()), nullable=False),
        sa.Column("importance", sa.SmallInteger(), server_default="2", nullable=True),
        sa.Column("difficulty", sa.SmallInteger(), server_default="2", nullable=True),
        sa.Column("confidence", sa.REAL(), nullable=False),
        sa.Column("derived", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("suspended", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("generation_status", sa.Text(), server_default="pending", nullable=True),
        sa.Column("norm_hash", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fragments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("material_id", sa.BigInteger(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("asset_id", sa.BigInteger(), nullable=True),
        sa.Column("locator", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quality", sa.REAL(), server_default="1.0", nullable=True),
        sa.Column("tokens", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["media_assets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_fragments_material_ord", "fragments", ["material_id", "ord"], unique=False)
    op.create_table(
        "questions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("fact_id", sa.BigInteger(), nullable=False),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("direction", sa.Text(), server_default="forward", nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("answer", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("difficulty", sa.SmallInteger(), server_default="2", nullable=False),
        sa.Column("status", sa.Text(), server_default="draft", nullable=True),
        sa.Column("reject_reason", sa.Text(), nullable=True),
        sa.Column("prompt_version", sa.Text(), nullable=True),
        sa.Column("model", sa.Text(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=True),
        sa.Column("generation_attempt", sa.Integer(), server_default="1", nullable=True),
        sa.Column("last_shown_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shown_count", sa.Integer(), server_default="0", nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["facts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_questions_fact_status", "questions", ["fact_id", "status"], unique=False)
    op.create_index(
        "ix_questions_fact_valid",
        "questions",
        ["fact_id"],
        unique=False,
        postgresql_where=sa.text("status = 'valid'"),
    )
    op.create_index(
        "uq_questions_fact_type_direction_valid",
        "questions",
        ["fact_id", "type", "direction"],
        unique=True,
        postgresql_where=sa.text("status = 'valid'"),
    )
    op.create_table(
        "review_states",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("fact_id", sa.BigInteger(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stability", sa.Double(), nullable=True),
        sa.Column("difficulty", sa.Double(), nullable=True),
        sa.Column("state", sa.SmallInteger(), nullable=True),
        sa.Column("reps", sa.Integer(), server_default="0", nullable=True),
        sa.Column("lapses", sa.Integer(), server_default="0", nullable=True),
        sa.Column("last_review", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_q_type", sa.Text(), nullable=True),
        sa.Column("last_direction", sa.Text(), nullable=True),
        sa.Column("seen", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("suspended", sa.Boolean(), server_default="false", nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("introduced_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "fact_id"),
    )
    op.create_index(
        "ix_review_states_user_due",
        "review_states",
        ["user_id", "due_at"],
        unique=False,
        postgresql_where=sa.text("NOT suspended"),
    )
    op.create_table(
        "quality_reports",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("question_id", sa.BigInteger(), nullable=True),
        sa.Column("fact_id", sa.BigInteger(), nullable=True),
        sa.Column("section_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "review_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("fact_id", sa.BigInteger(), nullable=False),
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("verdict", sa.Text(), nullable=True),
        sa.Column("scheduled_days", sa.Integer(), nullable=True),
        sa.Column("elapsed_days", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("fsrs_version", sa.Text(), nullable=False),
        sa.Column("planner_version", sa.Text(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "session_items",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("ord", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.BigInteger(), nullable=False),
        sa.Column("fact_id", sa.BigInteger(), nullable=False),
        sa.Column("user_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("answer_raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("verdict", sa.Text(), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["facts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("session_items")
    op.drop_table("review_logs")
    op.drop_table("quality_reports")
    op.drop_index(
        "ix_review_states_user_due",
        table_name="review_states",
        postgresql_where=sa.text("NOT suspended"),
    )
    op.drop_table("review_states")
    op.drop_index(
        "uq_questions_fact_type_direction_valid",
        table_name="questions",
        postgresql_where=sa.text("status = 'valid'"),
    )
    op.drop_index(
        "ix_questions_fact_valid",
        table_name="questions",
        postgresql_where=sa.text("status = 'valid'"),
    )
    op.drop_index("ix_questions_fact_status", table_name="questions")
    op.drop_table("questions")
    op.drop_index("ix_fragments_material_ord", table_name="fragments")
    op.drop_table("fragments")
    op.drop_table("facts")
    op.drop_index(
        "uq_sessions_user_active",
        table_name="sessions",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("sessions")
    op.drop_table("sections")
    op.drop_table("media_assets")
    op.drop_index(
        "uq_materials_user_sha256",
        table_name="materials",
        postgresql_where=sa.text("origin ? 'sha256'"),
    )
    op.drop_index("ix_materials_sha256", table_name="materials")
    op.drop_table("materials")
    op.drop_table("subjects")
    op.drop_table("users")
    op.drop_table("llm_calls")
    # ### end Alembic commands ###
